# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmZlMjIwMWNkMzJhNzM5NDdkZjJiNjliZjcwYjAzYjg4ZTYxM2M1M2NhOWRhNGI5MWRmZmNjZDJmOGNlYTEwMTJmNjIyNGNlZWMxZDc3MGQwN2I1ZTA3NGVhZjBjZGYyZjc4ZTZiMDRhMTA2NzQ4OTg1MzBmODVlZDRhMjY0Mjc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
